plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/root/.openclaw/workspace/ielts-vocab-deploy"
publishOrigin = "default"
base = "/root/.openclaw/workspace/ielts-vocab-deploy"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]